### PR TITLE
Remove table headers

### PR DESCRIPTION
**Pull request by tpoterba**
stacked on #16

### CODE REVIEW

**Comment by cseed** [comment]
Needs rebase now.

**Comment by tpoterba** [comment]
done

**Comment by cseed** [comment]
I feel like Github is esp. bad at this when the rebase would work fine.

**Comment by tpoterba** [comment]
I didn't `rebase` though, I `rebase --onto`ed

**Comment by tpoterba** [comment]
but yeah, the problem was that the PR was pointed at the wrong head I guess

**Pull request merged**
